### ISSUE TITLE
fix: E0716 in proxy_direct.rs breaks the autospec-cli unit-test and managed_project targets

### ISSUE THREAD

**Issue by berlinguyinca** [berlinguyinca/autospec#3475]
## Goal

Restore compilation of the `autospec-cli` `bin "autospec" test` and `test "managed_project"` targets by binding the `OsString` temporary before borrowing it.

## Problem

`cargo test -p autospec-cli --no-run` fails with **4× `error[E0716]: temporary value dropped while borrowed`**, all the same shape, in `crates/autospec-cli/src/commands/autonomous/executor_bridge/tests/proxy_direct.rs` (lines 175 and 220 among them):

```rust
let name = entry.file_name().to_string_lossy();
name.rsplit_once(".archive-").is_some_and(|(_, suffix)| !suffix.is_empty())
```

`entry.file_name()` returns an owned `OsString`; `.to_string_lossy()` borrows it; the temporary is freed at the end of the statement.

Result:

```
error: could not compile `autospec-cli` (bin "autospec" test) due to 2 previous errors
error: could not compile `autospec-cli` (test "managed_project") due to 2 previous errors
```

Introduced by #3461 (`fix: replace substring archive check with suffix-boundary rsplit`).

## Why this is higher priority than its size suggests

1. **It disables a whole test target.** Every `#[cfg(test)]` unit test inside `crates/autospec-cli/src/**` is unrunnable — not failing, *uncompilable*. New unit tests there cannot be executed at all. #3473 added a pin test for the issue-safety pattern allowlist in `commands/lint.rs` that is currently unenforceable for exactly this reason; it was verified only by temporarily patching this file and then reverting that patch.
2. **There is no CI backstop.** GitHub Actions has not run on this repo since 2026-08-20 — a `workflow_dispatch` run has been `queued` for 13 days, which indicates no available runner, and the last `rust-suites` run was `failure`. PR merges are currently satisfying "checks green" via GitGuardian alone. Local runs are the only real verification, so a non-compiling local target is the whole gate.

## Implementation outline

- Bind the `OsString` before borrowing, per the compiler's own suggestion, at each of the 4 sites:
  ```rust
  let file_name = entry.file_name();
  let name = file_name.to_string_lossy();
  ```
- Do not change the `.rsplit_once(".archive-")` suffix-boundary semantics from #3461 — this is a borrow-lifetime fix only.

## Tests required

- `cargo test -p autospec-cli --no-run` compiles cleanly (this is the regression signal).
- `cargo test -p autospec-cli` runs, including the `bin "autospec" test` unit target.
- The archive-suffix behavior from #3461 keeps its existing test coverage and verdicts.

### Primary smoke test

```bash
cargo test -p autospec-cli --no-run
```

## Files touched

- `crates/autospec-cli/src/commands/autonomous/executor_bridge/tests/proxy_direct.rs`
- `tests/unit/proxy-direct-borrow-lifetime.bats`
- `tests/smoke/autospec-cli-test-target-builds.bats`

## Out of scope

The pre-existing clippy errors in `crates/autospec-core/src/validation/structural.rs`, and restoring GitHub Actions runners.

## Acceptance criteria

- [ ] `cargo test -p autospec-cli --no-run` exits 0
- [ ] Both `bin "autospec" test` and `test "managed_project"` targets compile
- [ ] #3461's suffix-boundary semantics are unchanged

## Safety review

- **decision:** `SAFETY_PASS`

**Comment by berlinguyinca** [comment]
- **issue:** `3475`
- **decision:** `SAFETY_AMBIGUOUS`
- **findings:** weaken-security-control

**Comment by berlinguyinca** [comment]
{"schema":1,"repo":"berlinguyinca/autospec","issue":3475,"worker_id":"bender:wohlgemuth:claude:2872339","state":"claimed","branch":"fix/3475-e0716-proxy-direct","pr":"","step":"heartbeat-pending:39316531336665662d376339322d343532342d383738382d303938393037623634373937","paths":[],"claimed_at":"2026-09-02T22:30:19Z","updated_at":"2026-09-02T22:30:19Z","ttl_seconds":10800,"claim_id":"claim-2872342-1788388219971244514-1"}

**Comment by berlinguyinca** [comment]
{"schema":1,"repo":"berlinguyinca/autospec","issue":3475,"worker_id":"bender:wohlgemuth:claude:2872339","state":"claimed","branch":"fix/3475-e0716-proxy-direct","pr":"","step":"heartbeat-ready:39316531336665662d376339322d343532342d383738382d303938393037623634373937","paths":[],"claimed_at":"2026-09-02T22:30:19Z","updated_at":"2026-09-02T22:30:31Z","ttl_seconds":10800,"claim_id":"claim-2872342-1788388219971244514-1"}

**Comment by berlinguyinca** [comment]
{"schema":1,"repo":"berlinguyinca/autospec","issue":3475,"worker_id":"bender:wohlgemuth:claude:2872339","state":"claimed","branch":"fix/3475-e0716-proxy-direct","pr":"","step":"claimed","paths":[],"claimed_at":"2026-09-02T22:30:19Z","updated_at":"2026-09-02T22:31:00Z","ttl_seconds":10800,"claim_id":"claim-2872342-1788388219971244514-1"}

**Comment by berlinguyinca** [comment]
{"schema":1,"repo":"berlinguyinca/autospec","issue":3475,"worker_id":"bender:wohlgemuth:claude:2872339","state":"merged","branch":"fix/3475-e0716-proxy-direct","pr":"3476","step":"merged","paths":[],"claimed_at":"2026-09-02T22:30:19Z","updated_at":"2026-09-02T22:54:52Z","ttl_seconds":10800,"claim_id":"claim-2872342-1788388219971244514-1"}

**Comment by berlinguyinca** [comment]
{"schema":1,"repo":"berlinguyinca/autospec","issue":3475,"worker_id":"bender:wohlgemuth:claude:2872339","state":"merged","branch":"fix/3475-e0716-proxy-direct","pr":"3476","finalized_at":"2026-09-02T22:54:52Z"}
